let str = "Hello \"Mike\"";
console.log(str);

let str2 = 'Hello what\'s your name?';
console.log(str2);

let str3 = "New \nline.";
console.log(str3);

let str4 = "New \tline.";
console.log(str4);

let str5 = "New \\line.";
console.log(str5);

let str6 = "New \bline.";
console.log(str6);


// Code	Meaning
// \"	Double quote print kare
// \'	Single quote print kare
// \n	New line
// \\	Backslash print kare
// \b	Backspace
// \t	Tab
